#!/usr/bin/with-contenv bash

# install requirements
cd config
pip install -r requirements.txt

if [[ -v LOGLEVEL ]]; then
  exec s6-setuidgid abc python /RSScrawler.py --docker --log-level=$LOGLEVEL $PARAMETER
else
  exec s6-setuidgid abc python /RSScrawler.py --docker $PARAMETER
fi
